//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _IPC2_Practica2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.API")]
    public interface API {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/hello_worldRequest", ReplyAction="http://ws/API/hello_worldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string hello_world(string carnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/hello_worldRequest", ReplyAction="http://ws/API/hello_worldResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> hello_worldAsync(string carnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/crearEstudianteRequest", ReplyAction="http://ws/API/crearEstudianteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool crearEstudiante(int carnet_operario, int carnet, string nombres, string apellidos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/crearEstudianteRequest", ReplyAction="http://ws/API/crearEstudianteResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> crearEstudianteAsync(int carnet_operario, int carnet, string nombres, string apellidos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/crearEventoRequest", ReplyAction="http://ws/API/crearEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool crearEvento(int carnet_operario, string nombre_evento, string descripcion, string tipo_evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/crearEventoRequest", ReplyAction="http://ws/API/crearEventoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> crearEventoAsync(int carnet_operario, string nombre_evento, string descripcion, string tipo_evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/AsistirEventoRequest", ReplyAction="http://ws/API/AsistirEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool AsistirEvento(int carnet_operario, int id_evento, int carnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/AsistirEventoRequest", ReplyAction="http://ws/API/AsistirEventoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> AsistirEventoAsync(int carnet_operario, int id_evento, int carnet);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/MostrarEventosRequest", ReplyAction="http://ws/API/MostrarEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        _IPC2_Practica2.ServiceReference1.MostrarEventosResponse MostrarEventos(_IPC2_Practica2.ServiceReference1.MostrarEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/MostrarEventosRequest", ReplyAction="http://ws/API/MostrarEventosResponse")]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.MostrarEventosResponse> MostrarEventosAsync(_IPC2_Practica2.ServiceReference1.MostrarEventosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/getTiposDeEventoRequest", ReplyAction="http://ws/API/getTiposDeEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        _IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse getTiposDeEvento(_IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/getTiposDeEventoRequest", ReplyAction="http://ws/API/getTiposDeEventoResponse")]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse> getTiposDeEventoAsync(_IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/getEstudiantesRequest", ReplyAction="http://ws/API/getEstudiantesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        _IPC2_Practica2.ServiceReference1.getEstudiantesResponse getEstudiantes(_IPC2_Practica2.ServiceReference1.getEstudiantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/API/getEstudiantesRequest", ReplyAction="http://ws/API/getEstudiantesResponse")]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getEstudiantesResponse> getEstudiantesAsync(_IPC2_Practica2.ServiceReference1.getEstudiantesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int id_eventoField;
        
        private string nombreField;
        
        private string tipoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_evento {
            get {
                return this.id_eventoField;
            }
            set {
                this.id_eventoField = value;
                this.RaisePropertyChanged("id_evento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class estudiante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private int carnetField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int carnet {
            get {
                return this.carnetField;
            }
            set {
                this.carnetField = value;
                this.RaisePropertyChanged("carnet");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostrarEventos", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class MostrarEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int carnet_operario;
        
        public MostrarEventosRequest() {
        }
        
        public MostrarEventosRequest(int carnet_operario) {
            this.carnet_operario = carnet_operario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MostrarEventosResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class MostrarEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public _IPC2_Practica2.ServiceReference1.evento[] @return;
        
        public MostrarEventosResponse() {
        }
        
        public MostrarEventosResponse(_IPC2_Practica2.ServiceReference1.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTiposDeEvento", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getTiposDeEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int carnet_operario;
        
        public getTiposDeEventoRequest() {
        }
        
        public getTiposDeEventoRequest(int carnet_operario) {
            this.carnet_operario = carnet_operario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTiposDeEventoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getTiposDeEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getTiposDeEventoResponse() {
        }
        
        public getTiposDeEventoResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstudiantes", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getEstudiantesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int carnet_operario;
        
        public getEstudiantesRequest() {
        }
        
        public getEstudiantesRequest(int carnet_operario) {
            this.carnet_operario = carnet_operario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstudiantesResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class getEstudiantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public _IPC2_Practica2.ServiceReference1.estudiante[] @return;
        
        public getEstudiantesResponse() {
        }
        
        public getEstudiantesResponse(_IPC2_Practica2.ServiceReference1.estudiante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIChannel : _IPC2_Practica2.ServiceReference1.API, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIClient : System.ServiceModel.ClientBase<_IPC2_Practica2.ServiceReference1.API>, _IPC2_Practica2.ServiceReference1.API {
        
        public APIClient() {
        }
        
        public APIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string hello_world(string carnet) {
            return base.Channel.hello_world(carnet);
        }
        
        public System.Threading.Tasks.Task<string> hello_worldAsync(string carnet) {
            return base.Channel.hello_worldAsync(carnet);
        }
        
        public bool crearEstudiante(int carnet_operario, int carnet, string nombres, string apellidos) {
            return base.Channel.crearEstudiante(carnet_operario, carnet, nombres, apellidos);
        }
        
        public System.Threading.Tasks.Task<bool> crearEstudianteAsync(int carnet_operario, int carnet, string nombres, string apellidos) {
            return base.Channel.crearEstudianteAsync(carnet_operario, carnet, nombres, apellidos);
        }
        
        public bool crearEvento(int carnet_operario, string nombre_evento, string descripcion, string tipo_evento) {
            return base.Channel.crearEvento(carnet_operario, nombre_evento, descripcion, tipo_evento);
        }
        
        public System.Threading.Tasks.Task<bool> crearEventoAsync(int carnet_operario, string nombre_evento, string descripcion, string tipo_evento) {
            return base.Channel.crearEventoAsync(carnet_operario, nombre_evento, descripcion, tipo_evento);
        }
        
        public bool AsistirEvento(int carnet_operario, int id_evento, int carnet) {
            return base.Channel.AsistirEvento(carnet_operario, id_evento, carnet);
        }
        
        public System.Threading.Tasks.Task<bool> AsistirEventoAsync(int carnet_operario, int id_evento, int carnet) {
            return base.Channel.AsistirEventoAsync(carnet_operario, id_evento, carnet);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_Practica2.ServiceReference1.MostrarEventosResponse _IPC2_Practica2.ServiceReference1.API.MostrarEventos(_IPC2_Practica2.ServiceReference1.MostrarEventosRequest request) {
            return base.Channel.MostrarEventos(request);
        }
        
        public _IPC2_Practica2.ServiceReference1.evento[] MostrarEventos(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.MostrarEventosRequest inValue = new _IPC2_Practica2.ServiceReference1.MostrarEventosRequest();
            inValue.carnet_operario = carnet_operario;
            _IPC2_Practica2.ServiceReference1.MostrarEventosResponse retVal = ((_IPC2_Practica2.ServiceReference1.API)(this)).MostrarEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.MostrarEventosResponse> _IPC2_Practica2.ServiceReference1.API.MostrarEventosAsync(_IPC2_Practica2.ServiceReference1.MostrarEventosRequest request) {
            return base.Channel.MostrarEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.MostrarEventosResponse> MostrarEventosAsync(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.MostrarEventosRequest inValue = new _IPC2_Practica2.ServiceReference1.MostrarEventosRequest();
            inValue.carnet_operario = carnet_operario;
            return ((_IPC2_Practica2.ServiceReference1.API)(this)).MostrarEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse _IPC2_Practica2.ServiceReference1.API.getTiposDeEvento(_IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest request) {
            return base.Channel.getTiposDeEvento(request);
        }
        
        public string[] getTiposDeEvento(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest inValue = new _IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest();
            inValue.carnet_operario = carnet_operario;
            _IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse retVal = ((_IPC2_Practica2.ServiceReference1.API)(this)).getTiposDeEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse> _IPC2_Practica2.ServiceReference1.API.getTiposDeEventoAsync(_IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest request) {
            return base.Channel.getTiposDeEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getTiposDeEventoResponse> getTiposDeEventoAsync(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest inValue = new _IPC2_Practica2.ServiceReference1.getTiposDeEventoRequest();
            inValue.carnet_operario = carnet_operario;
            return ((_IPC2_Practica2.ServiceReference1.API)(this)).getTiposDeEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_Practica2.ServiceReference1.getEstudiantesResponse _IPC2_Practica2.ServiceReference1.API.getEstudiantes(_IPC2_Practica2.ServiceReference1.getEstudiantesRequest request) {
            return base.Channel.getEstudiantes(request);
        }
        
        public _IPC2_Practica2.ServiceReference1.estudiante[] getEstudiantes(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.getEstudiantesRequest inValue = new _IPC2_Practica2.ServiceReference1.getEstudiantesRequest();
            inValue.carnet_operario = carnet_operario;
            _IPC2_Practica2.ServiceReference1.getEstudiantesResponse retVal = ((_IPC2_Practica2.ServiceReference1.API)(this)).getEstudiantes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getEstudiantesResponse> _IPC2_Practica2.ServiceReference1.API.getEstudiantesAsync(_IPC2_Practica2.ServiceReference1.getEstudiantesRequest request) {
            return base.Channel.getEstudiantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_Practica2.ServiceReference1.getEstudiantesResponse> getEstudiantesAsync(int carnet_operario) {
            _IPC2_Practica2.ServiceReference1.getEstudiantesRequest inValue = new _IPC2_Practica2.ServiceReference1.getEstudiantesRequest();
            inValue.carnet_operario = carnet_operario;
            return ((_IPC2_Practica2.ServiceReference1.API)(this)).getEstudiantesAsync(inValue);
        }
    }
}
